django_train_1/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.views.static import serve
from django.conf import settings

from memberapp.views import depart, member, pretty, admin, accout, task, order, echarts, upload, city

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    path('login/', accout.login),
    path('logout/', accout.logout),

    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),

    path('depart/list/', depart.departList),
    path('depart/add/', depart.departAdd),
    path('depart/delete/', depart.departDelete),
    path('depart/<int:nid>/edit', depart.departEdit),

    path('member/list/', member.memberlist),
    path('member/add/', member.memberadd),
    path('member/<int:nid>/edit/', member.memberedit),
    path('member/<int:nid>/delete/', member.memberdelete),

    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),

    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),

    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),

    path('echarts/list/', echarts.echarts_edit),

    path('upload/list/', upload.upload_edit),
    path('upload/form/', upload.upload_form),
    path('upload/modelform/', upload.upload_modelform),

    path('city/list', city.city_list),
]

memberapp/models.py
from django.db import models


# Create your models here.

class Admin(models.Model):
    name = models.CharField(verbose_name="账号", max_length=32)
    pwd = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(verbose_name="部门名", max_length=16)

    def __str__(self):
        return self.name


class Member(models.Model):
    gender_list = (
        (1, "男"),
        (2, "女")
    )

    name = models.CharField(verbose_name="名字", max_length=16)
    phone = models.CharField(verbose_name="手机号", max_length=32)
    pwd = models.CharField(verbose_name="密码", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="余额", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateTimeField(verbose_name="入职时间", null=True, blank=True)

    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", null=True, blank=True,
                               on_delete=models.SET_NULL)
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_list)


class PrettyNum(models.Model):
    """ 靓号表 """
    level_choices = (
        (1, "一级"),
        (2, "二级"),
        (3, "三级"),
        (4, "四级"),
    )

    status_choices = {
        (1, "已占用"),
        (2, "未使用"),
    }

    mobile = models.CharField(verbose_name="号码", max_length=11)
    price = models.IntegerField(verbose_name="价格", default=0)
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


class Task(models.Model):
    level_choices = (
        (1, '紧急'),
        (2, '重要'),
        (3, '临时'),
    )

    level = models.SmallIntegerField(verbose_name="等级", choices=level_choices, default=3)
    title = models.CharField(verbose_name="标题", max_length=64)
    details = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)


class Order(models.Model):
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=64)
    price = models.IntegerField(verbose_name="价格", default=0)

    status_choices = (
        (1, '待支付'),
        (2, '已支付'),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE)


class Userdata(models.Model):
    name = models.CharField(verbose_name="昵称", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    avatar = models.CharField(verbose_name="头像", max_length=128)


class City(models.Model):
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")

    # 本质上数据库上也是CharField，自动保存数据。
    img = models.FileField(verbose_name="logo", max_length=128, upload_to='city/')
    # upload_to='city/' : 文件保存到 'media/city/' 目录下

memberapp/views/accout.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django import forms

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.BootstrapModelForm import BootstrapModelForm, BootstrapForm
from memberapp.utils.encrypt import md5
from memberapp.utils.form import MemberForm, PrettyForm, PrettyEditForm


class LoginForm(BootstrapForm):
    name = forms.CharField(label='账号', widget=forms.TextInput())
    pwd = forms.CharField(label='账号', widget=forms.PasswordInput())

    def clean_pwd(self):
        return md5(self.cleaned_data['pwd'])


def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(request.POST)
    if form.is_valid():
        user_obj = models.Admin.objects.filter(**form.cleaned_data).first()
        if user_obj:
            print("查找成功")
            request.session['info'] = {'id': user_obj.id, 'name': user_obj.name}
            return redirect('/admin/list')
        print("查找失败")
        form.add_error('name', '用户名或密码错误')
    return render(request, 'login.html', {'form': form})


def logout(request):
    request.session.clear()
    return redirect('/login/')

memberapp/views/admin.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django import forms

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.BootstrapModelForm import BootstrapModelForm
from memberapp.utils.encrypt import md5
from memberapp.utils.form import MemberForm, PrettyForm, PrettyEditForm


def admin_list(request):
    search_dict = {}
    search_data = request.GET.get('q', '')
    if search_data:
        search_dict['name__contains'] = search_data

    queryset = models.Admin.objects.filter(**search_dict)
    page_obj = Pagination(request, queryset)
    context = {
        'admin_list': page_obj.queryset_list,
        'page_code': page_obj.html(),
        'search_data': search_data,
    }
    return render(request, 'admin_list.html', context)


class AdminForm(BootstrapModelForm):
    confirm_pwd = forms.CharField(label='确认密码', widget=forms.PasswordInput)

    class Meta:
        model = models.Admin
        fields = ['name', 'pwd', 'confirm_pwd']
        widgets = {
            'pwd': forms.PasswordInput(render_value=True)
        }

    def clean_pwd(self):
        pwd = self.cleaned_data['pwd']
        return md5(pwd)

    def clean_confirm_pwd(self):
        confirm_pwd = md5(self.cleaned_data['confirm_pwd'])
        pwd = self.cleaned_data['pwd']
        if confirm_pwd != pwd:
            raise ValidationError("两次密码不一致")
        return confirm_pwd

def admin_add(request):
    if request.method == 'GET':
        form = AdminForm()
        context = {
            'title_name': "新增管理员",
            'form': form,
        }
        return render(request, 'changes.html', context)

    form = AdminForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    context = {
        'title_name': "新增管理员",
        'form': form,
    }
    return render(request, 'changes.html', context)

memberapp/views/city.py
import json
import os

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.BootstrapModelForm import BootstrapModelForm


class CityModelForm(BootstrapModelForm):
    class Meta:
        model = models.City
        fields = '__all__'


def city_list(request):
    if request.method == 'GET':
        queryset = models.City.objects.all()
        form = CityModelForm()
        page_obj = Pagination(request, queryset, page_size=5)
        context = {
            'form': form,
            'city_list': page_obj.queryset_list,
            'page_code': page_obj.html(),
        }
        return render(request, 'city_list.html', context)

memberapp/views/depart.py
from django.shortcuts import render, redirect

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.form import MemberForm, PrettyForm, PrettyEditForm


# Create your views here.
def departList(request):
    if request.method == 'GET':
        departs_list = models.Department.objects.all()
        return render(request, 'departlist.html', {'departs_list': departs_list})


def departAdd(request):
    if request.method == 'GET':
        return render(request, 'departadd.html')

    name = request.POST.get('name')
    models.Department.objects.create(name=name)
    return redirect('/depart/list/')


def departDelete(request):
    nid = request.GET.get("nid")
    models.Department.objects.filter(id=nid).delete()

    return redirect('/depart/list/')


def departEdit(request, nid):
    if request.method == 'GET':
        depart = models.Department.objects.filter(id=nid).first()
        return render(request, 'departedit.html', {"depart": depart})

    name = request.POST.get('name')
    models.Department.objects.filter(id=nid).update(name=name)
    return redirect('/depart/list/')

memberapp/views/echarts.py
from django.shortcuts import render, redirect

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.form import MemberForm, PrettyForm, PrettyEditForm


def echarts_edit(request):
    return render(request, 'echarts_list.html')

memberapp/views/member.py
from django.shortcuts import render, redirect

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.form import MemberForm, PrettyForm, PrettyEditForm


def memberlist(request):
    member_list = models.Member.objects.all()
    pagination_obj = Pagination(request, member_list)

    context = {
        'member_list': pagination_obj.queryset_list,
        'page_code': pagination_obj.html(),
    }

    return render(request, 'memberlist.html', context)


def memberadd(request):
    if request.method == 'GET':
        form = MemberForm()
        return render(request, 'memberadd.html', {"form": form})

    form = MemberForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/member/list/')

    return render(request, 'memberadd.html', {"form": form})


def memberedit(request, nid):
    row_obj = models.Member.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = MemberForm(instance=row_obj)
        return render(request, 'memberedit.html', {'form': form})

    form = MemberForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect('/member/list/')

    return render(request, 'memberedit.html', {"form": form})


def memberdelete(request, nid):
    models.Member.objects.filter(id=nid).delete()
    return redirect('/member/list/')

memberapp/views/order.py
import random
from datetime import datetime

from django import forms
from django.http import JsonResponse
from django.shortcuts import render, redirect

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.form import MemberForm, PrettyForm, PrettyEditForm
from memberapp.utils.BootstrapModelForm import BootstrapModelForm
from django.views.decorators.csrf import csrf_exempt


class OrderForm(BootstrapModelForm):
    class Meta:
        model = models.Order
        exclude = ['oid', 'admin']


def order_list(request):
    form = OrderForm()

    orders = models.Order.objects.all().order_by('-id')
    page_obj = Pagination(request, orders)
    context = {
        'order_list': page_obj.queryset_list,
        'page_code': page_obj.html(),
        'form': form
    }
    return render(request, 'order_list.html', context)


@csrf_exempt
def order_add(request):
    form = OrderForm(request.POST)
    form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))
    if form.is_valid():
        form.instance.admin_id = request.session['info']['id']
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'errors': form.errors})


def order_delete(request):
    print(request.GET)
    models.Order.objects.filter(id=int(request.GET.get('q'))).delete()
    return JsonResponse({})


def order_detail(request):
    uid = request.GET.get('uid')
    data_dict = models.Order.objects.filter(id=uid).values('oid', 'title', 'price', 'status').first()
    return JsonResponse({'status': True, 'data': data_dict})


@csrf_exempt
def order_edit(request):
    uid = request.GET.get('uid')
    row_obj = models.Order.objects.filter(id=uid).first()
    if row_obj is None:
        print('no rowobj')
        return JsonResponse({'status': False})
    form = OrderForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'errors': form.errors})

memberapp/views/pretty.py
from django.shortcuts import render, redirect

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.form import MemberForm, PrettyForm, PrettyEditForm


def pretty_list(request):
    # for i in range(300):
    #     models.PrettyNum.objects.create(mobile="18838828898")

    search_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        search_dict['mobile__contains'] = search_data

    # 分页功能
    queryset = models.PrettyNum.objects.filter(**search_dict).order_by('-level')
    paginator_object = Pagination(request, queryset)

    prtty_list = paginator_object.queryset_list
    page_code = paginator_object.html()

    context = {
        "pretty_list": prtty_list,
        "search_data": search_data,
        "page_code": page_code
    }
    return render(request, 'prtty_list.html', context)


def pretty_add(request):
    if request.method == 'GET':
        pretty_form = PrettyForm()
        return render(request, 'pretty_add.html', {"form": pretty_form})

    form_get = PrettyForm(data=request.POST)
    if form_get.is_valid():
        form_get.save()
        return redirect('/pretty/list/')
    return render(request, 'pretty_add.html', {"form": form_get})


def pretty_edit(request, nid):
    row_object = models.PrettyNum.objects.get(id=nid)
    form = PrettyEditForm(instance=row_object)
    if request.method == 'GET':
        return render(request, 'pretty_edit.html', {"form": form})

    form_get = PrettyEditForm(data=request.POST, instance=row_object)
    if form_get.is_valid():
        form_get.save()
        return redirect('/pretty/list/')
    return render(request, 'pretty_edit.html', {"form": form_get})


def pretty_delete(request, nid):
    models.PrettyNum.objects.get(id=nid).delete()
    return redirect('/pretty/list/')

memberapp/views/task.py
import json

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from memberapp import models
from memberapp.utils.pagination import Pagination
from memberapp.utils.BootstrapModelForm import BootstrapModelForm


class TaskForm(BootstrapModelForm):
    class Meta:
        model = models.Task
        fields = '__all__'


def task_list(request):
    form = TaskForm()
    if request.method == 'GET':
        return render(request, 'task_list.html', {"form": form})


@csrf_exempt
def task_ajax(request):
    print(request.POST)
    data_dict = {'status': True, 'data': [1, 1, 2, 2]}
    return HttpResponse(json.dumps(request.POST))
    # 或者return JsonResponse(dict)


@csrf_exempt
def task_add(request):
    form = TaskForm(request.POST)
    if form.is_valid():
        form.save()
        data_dict = {'status': True}
    else:
        data_dict = {'status': False, 'error': form.errors}

    return HttpResponse(json.dumps(data_dict))

memberapp/templates/admin_list.html
{% extends "layout.html" %}

{% block contend %}
    <h4>管理员列表</h4>
    <div class="clearfix">
        <a href="/admin/add/" class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
            </svg>
            新增管理员</a>
        <div style="float: right; width: 15rem">
            <form class="d-flex" role="search" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q"
                       value={{ search_data }}>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>

    <div class="card text-center" style="margin-top: 1rem">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">账号</th>
                <th scope="col">密码</th>
                <th scope="col">操作</th>
            </tr>
            </thead>

            <tbody>
            {% for obj in admin_list %}
                <tr>
                    <th scope="col">{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                    <td>******</td>
                    <td>
                        <a href="/member/{{ obj.id }}/edit" class="btn btn-sm btn-primary"
                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .8rem;">编辑</a>
                        <a href="/member/{{ obj.id }}/delete" class="btn btn-sm btn-danger"
                           style="margin-left: .5rem;--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .8rem;">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {{ page_code }}
            </ul>
        </nav>
    </div>
{% endblock %}

memberapp/templates/memberadd.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block contend %}
    <div class="text-center"><span style="font-size: 1.5rem">新增用户</span></div>
    <div class="card container-fluid text-center py-3 mt-2" style="width:50rem">
        <div class="row justify-content-md-center">
            <div class="col-md-11">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="row mb-3">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                            </div>
                            <span style="color: red">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-success">新 增</button>
                </form>


            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function(){
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autolose: true
            });

        })
    </script>
{% endblock %}

memberapp/templates/memberlist.html
{% extends "layout.html" %}

{% block contend %}
    <h4>用户列表</h4>
    <a href="/member/add/" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
             class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
        </svg>
        新增用户</a>
    <div class="card text-center" style="margin-top: 1rem">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">名字</th>
                <th scope="col">手机号</th>
                <th scope="col">密码</th>
                <th scope="col">年龄</th>
                <th scope="col">余额</th>
                <th scope="col">性别</th>
                <th scope="col">部门</th>
                <th scope="col">入职时间</th>
                <th scope="col">操作</th>
            </tr>
            </thead>

            <tbody>
            {% for obj in member_list %}
                <tr>
                    <th scope="col">{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.phone }}</td>
                    <td>{{ obj.pwd }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.account }}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.depart.name }}</td>
                    <td>{{ obj.create_time|date:"Y-m-d H:i:s" }}</td>
                    <td>
                        <a href="/member/{{ obj.id }}/edit" class="btn btn-sm btn-primary"
                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .8rem;">编辑</a>
                        <a href="/member/{{ obj.id }}/delete" class="btn btn-sm btn-danger"
                           style="margin-left: .5rem;--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .8rem;">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {{ page_code }}
            </ul>
        </nav>
    </div>
{% endblock %}

memberapp/templates/order_list.html
{% extends 'layout.html' %}

{% block contend %}
    <div class="container">
        <h2 class="mb-3">工单管理</h2>
        <input type="button" id="modal_btn" class="btn btn-success" value="新 建 工 单">
    </div>

    <div class="container">
        <div class="card text-center" style="margin-top: .5rem;width: 50rem">
            <table class="table table-striped table-bordered align-middle">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">订单号</th>
                    <th scope="col">订单名</th>
                    <th scope="col">价格</th>
                    <th scope="col">状态</th>
                    <th scope="col">管理人</th>
                    <th scope="col">操作</th>
                </tr>
                </thead>

                <tbody>
                {% for obj in order_list %}
                    <tr>
                        <th scope="col">{{ obj.id }}</th>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.admin }}</td>
                        <td>
                            <button uid="{{ obj.id }}" class="btn btn-sm btn-primary ac_sm_btn btn_edit">编辑</button>
                            <button uid="{{ obj.id }}" class="btn btn-sm btn-danger ac_sm_btn btn_delete"
                                    style="margin-left: .5rem">删除
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">

                    {{ page_code }}
                </ul>
            </nav>
        </div>
    </div>

    <!-- 弹窗1: 新建 -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">新建工单</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-4 pt-1">
                        <label for="id_oid" class="col-sm-2 col-form-label">订单号</label>
                        <div class="col-sm-10" style="position: relative">
                            <input type="text" class="form-control" placeholder="自动生成" id="id_oid" disabled="disabled">
                        </div>

                    </div>
                    <form id="order_form">
                        {% for field in form %}
                            <div class="row mb-4 pt-1">
                                <label for="inputEmail3" class="col-sm-2 col-form-label">{{ field.label }}</label>
                                <div class="col-sm-10" style="position: relative">
                                    {{ field }}
                                    <span class="error-msg" style="color: red; position: absolute;left: .75rem"></span>
                                </div>

                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关 闭</button>
                    <button type="button" class="btn btn-success" id="btn_save">保 存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 弹窗2: 删除 -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="alert alert-danger m-0" role="alert">
                    <h4 class="alert-heading">删除</h4>
                    <p>是否确定删除?</p>
                    <hr>
                    <p class="mb-0" style="text-align: right">
                        <button type="button" class="btn btn-light mx-2" data-bs-dismiss="modal">取 消</button>
                        <button type="button" class="btn btn-danger" id="btn_in_delete">删 除</button>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID
        var EDIT_ID

        $(function () {
            BindBtnModal1();
            BindBtnSaveEvent();
            BindBtnDeleteModalEvent();
            BindBtnDeleteEvent();
            BindBtnEditModelEvent();
        })


        function BindBtnModal1() {
            $("#modal_btn").click(function () {
                $("#exampleModalLabel").text('新建工单')
                $("#id_oid").val('')
                EDIT_ID = undefined;
                $('#order_form')[0].reset();

                $("#exampleModal").modal('show');
            })
        }

        function BindBtnSaveEvent() {
            $('#btn_save').click(function () {

                if (EDIT_ID) {
                    console.log('EDIT')
                    do_edit();
                } else {
                    console.log('ADD')
                    do_add();
                }

            })
        }

        function BindBtnDeleteModalEvent() {
            $(".btn_delete").click(function () {
                $("#deleteModal").modal('show');

                DELETE_ID = $(this).attr("uid");
            })
        }

        function BindBtnDeleteEvent() {
            $("#btn_in_delete").click(function () {
                $.ajax({
                    url: '/order/delete/',
                    type: 'get',
                    data: {q: DELETE_ID},
                    dataType: "JSON",
                    success: function (res) {
                        $("#deleteModal").modal('hide')
                        console.log('shanchu')
                        location.reload()
                    }
                })
            })
        }

        function BindBtnEditModelEvent() {
            $(".btn_edit").click(function () {
                EDIT_ID = $(this).attr("uid");
                $("#exampleModalLabel").text('编辑工单');
                $.ajax({
                    url: '/order/detail/',
                    type: 'get',
                    data: {uid: EDIT_ID},
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            $("#order_form")[0].reset()
                            $.each(res.data, function (name, value) {
                                $("#id_" + name).val(value)
                            })
                            $("#exampleModal").modal('show');
                        }
                    }
                })


            })
        }

        function do_add() {
            $.ajax({
                url: '/order/add/',
                type: 'post',
                data: $("#order_form").serialize(),
                dataType: "JSON",
                success: function (res) {
                    $(".error-msg").empty()
                    if (res.status) {
                        $("#exampleModal").modal('hide');
                        location.reload()
                    } else {
                        $.each(res.errors, function (key, value) {
                            $("#id_" + key).next().text(value);
                        })
                    }
                }
            })
        }

        function do_edit() {
            $.ajax({
                url: '/order/edit/' + '?uid=' + EDIT_ID,
                type: 'post',
                data: $("#order_form").serialize(),
                dataType: "JSON",
                success: function (res) {
                    $(".error-msg").empty()
                    if (res.status) {
                        $('#order_form')[0].reset();
                        $("#exampleModal").modal('hide');
                        location.reload()
                    } else {
                        $.each(res.errors, function (key, value) {
                            $("#id_" + key).next().text(value);
                        })
                    }
                }
            })
        }

    </script>
{% endblock %}